version: "3.7"

x-defaults: &defaults
  image: driftwood/fracfocus
  restart: unless-stopped
  env_file: .env.compose
services:
  web:
    <<: *defaults
    command: fracfocus run web -b 0.0.0.0:9091
    ports:
      - "9091:9091"
