"""empty message

Revision ID: 0395eda87251
Revises: 84e14e92ad25
Create Date: 2019-12-30 11:36:38.870888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0395eda87251'
down_revision = '84e14e92ad25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_registry_updated_at'), 'registry', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registry_updated_at'), table_name='registry')
    # ### end Alembic commands ###
