"""empty message

Revision ID: 0939e60510fd
Revises: 10f881dcc11b
Create Date: 2019-12-29 16:13:23.726701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0939e60510fd'
down_revision = '10f881dcc11b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('registry_id_key', 'registry', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('registry_id_key', 'registry', ['id'])
    # ### end Alembic commands ###
