"""empty message

Revision ID: 20d2e25ee1bf
Revises: 3e69bf0d673a
Create Date: 2019-12-30 11:48:35.601361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d2e25ee1bf'
down_revision = '3e69bf0d673a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_registry_updated_at'), 'registry', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registry_updated_at'), table_name='registry')
    # ### end Alembic commands ###
