"""empty message

Revision ID: 2c41d311c1dd
Revises: 20d2e25ee1bf
Create Date: 2019-12-30 11:58:59.400542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2c41d311c1dd"
down_revision = "20d2e25ee1bf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_registry_updated_at", table_name="registry")
    # ### end Alembic commands ###

    # create updated_at trigger function
    op.execute(
        """
            create function set_updated_at(
                                        ) returns trigger
                language plpgsql
            as
            $$
            BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
            END;
            $$;
    """
    )

    # add trigger to registry.updated_at
    op.execute(
        """
    create trigger tg_registry_updated_at
	before update
	on registry
	for each row
	execute procedure set_updated_at();
    """
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_registry_updated_at", "registry", ["updated_at"], unique=False)
    op.execute("drop trigger if exists tg_registry_updated_at on registry;")
    op.execute("drop function if exists set_updated_at;")
    # ### end Alembic commands ###
