"""empty message

Revision ID: 32983281204f
Revises: 2c41d311c1dd
Create Date: 2019-12-30 12:35:15.863689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32983281204f'
down_revision = '2c41d311c1dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('registry_id_key', 'registry', type_='unique')
    op.drop_column('registry', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registry', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('registry_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.create_unique_constraint('registry_id_key', 'registry', ['id'])
    # ### end Alembic commands ###
