"""empty message

Revision ID: 443c95eca738
Revises: 0395eda87251
Create Date: 2019-12-30 11:40:53.976338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443c95eca738'
down_revision = '0395eda87251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_registry_updated_at', table_name='registry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_registry_updated_at', 'registry', ['updated_at'], unique=False)
    # ### end Alembic commands ###
