"""empty message

Revision ID: 4d5a7f435434
Revises: 443c95eca738
Create Date: 2019-12-30 11:44:47.649114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d5a7f435434'
down_revision = '443c95eca738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_registry_updated_at'), 'registry', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registry_updated_at'), table_name='registry')
    # ### end Alembic commands ###
