"""empty message

Revision ID: 84e14e92ad25
Revises: 37c8ce16ff47
Create Date: 2019-12-30 11:31:04.114468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84e14e92ad25'
down_revision = '37c8ce16ff47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_registry_api14'), 'registry', ['api14'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registry_api14'), table_name='registry')
    # ### end Alembic commands ###
