"""empty message

Revision ID: ae069a9aeeec
Revises: 32983281204f
Create Date: 2019-12-30 17:11:18.462594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ae069a9aeeec"
down_revision = "32983281204f"
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_registry_api10', table_name='registry')
    # op.drop_column("registry", "api10")
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column(
    #     "registry",
    #     sa.Column("api10", sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    # )
    # op.create_index('ix_registry_api10', 'registry', ['api10'], unique=False)
    # ### end Alembic commands ###
