"""empty message

Revision ID: ef074201f4ed
Revises: ae069a9aeeec
Create Date: 2019-12-30 17:12:57.280855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef074201f4ed'
down_revision = 'ae069a9aeeec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registry', sa.Column('api10', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_registry_api10'), 'registry', ['api10'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registry_api10'), table_name='registry')
    op.drop_column('registry', 'api10')
    # ### end Alembic commands ###
